name: Docker-build-metrics
defaults:
  run:
    working-directory: ./
on:
  push:
    paths:
<<<<<<< HEAD:.github/workflows/dist-immune-build.yml
      - 'metrics/distance/*'
      - 'metrics/imm-subtypes/*'
=======
      - 'metrics/*'
      - 'metrics/*/*'
      - 'simulatedData/*'
      - 'signatureMatrices/*'
>>>>>>> main:.github/workflows/metrics-docker-build.yml

jobs:
  build-and-push-tools:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push distance
        uses: docker/build-push-action@v4
        with:
          context: metrics/distance
          platforms: linux/amd64,linux/arm64
          push: true
          tags: tumordeconv/comparison:latest
      - name: Build and push immune subtype
        uses: docker/build-push-action@v4
        with:
          context: metrics/imm-subtypes
          platforms: linux/amd64,linux/arm64
          push: true
          tags: tumordeconv/imm-subtypes:latest

