name: Accessory-docker-build
defaults:
  run:
    working-directory: ./
on:
  push:
    branches:
      - "*"

jobs:
  build-and-push-deconv-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push imputation
        uses: docker/build-push-action@v2
        with:
          context: imputation
          push: true
          tags: tumordeconv/imputation:latest
      - name: Build and push mRNAData
        uses: docker/build-push-action@v2
        with:
          context: mRNAData
          push: true
          tags: tumordeconv/mrna-data:latest
