name: prot-matrix-sim-docker
defaults:
  run:
    working-directory: ./
on:
  push:
    branches:
      - "protData/*"
      - "signature_matrices/*"
      - "simulatedData/*"

jobs:
  build-and-push-protData-sig-sim:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push protData
        uses: docker/build-push-action@v4
        with:
          context: protData
          platforms: linux/amd64,linux/arm64
          push: true
          tags: tumordeconv/prot-data:latest
      - name: Build and push sig matrix
        uses: docker/build-push-action@v4
        with:
          context: signature_matrices
          platforms: linux/amd64,linux/arm64
          push: true
          tags: tumordeconv/signature_matrices:latest
      - name: Build and push simulated data
        uses: docker/build-push-action@v4
        with:
          context: simulatedData
          platforms: linux/amd64,linux/arm64
          push: true
          tags: tumordeconv/sim-data
