name: Accessory-docker-build
defaults:
  run:
    working-directory: ./
on:
  push:
    branches:
      - "*"

jobs:
  build-and-push-deconv-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push imputation
        uses: docker/build-push-action@v2
        with:
          context: imputation
          push: true
          tags: tumordeconv/imputation:latest
      - name: Build and push mRNAData
        uses: docker/build-push-action@v2
        with:
          context: mRNAData
          push: true
          tags: tumordeconv/mrna-data:latest
      - name: Build and push protData
        uses: docker/build-push-action@v2
        with:
          context: protData
          push: true
          tags: tumordeconv/prot-data:latest
      - name: Build and push sig matrix
        uses: docker/build-push-action@v2
        with:
          context: signature_matrices
          push: true
          tags: tumordeconv/signature_matrices:latest
      - name: Build and push simulated data
        uses: docker/build-push-action@v2
        with:
         context: simulatedData
         push: true
         tags: tumordeconv/sim-data
      #- name: docker pull
      #  run: "docker pull sgosline/srp-analytics"
      #- name: test LPR
      #  run: "docker run -v $PWD:/tmp sgosline/srp-analytics --test-lpr"
      #- name: test morpho
      #  run: "docker run -v $PWD:/tmp sgosline/srp-analytics --test-morpho"
      #- name: build db
      #  run: "docker run -v $PWD:/tmp sgosline/srp-analytics"
      #- name: validate schemas
      #  run: "docker run -v $PWD:/tmp sgosline/srp-analytics --validate"
