name: Docker-build-metrics
defaults:
  run:
    working-directory: ./
on:
  push:
    paths:
      - 'metrics/figures/*'
      - 'metrics/correlation/*'

jobs:
  build-and-push-tools:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push correlations
        uses: docker/build-push-action@v4
        with:
          context: metrics/correlations
          platforms: linux/amd64,linux/arm64
          push: true
          tags: tumordeconv/correlation:latest
      - name: Build and push figures
        uses: docker/build-push-action@v4
        with:
          context: metrics/figures
          platforms: linux/amd64,linux/arm64
          push: true
          tags: tumordeconv/figures:latest

